name: extended_value_notifier
description: A package that can make ValueNotifier easier to use.
version: 0.0.1
homepage: 'https://github.com/AAAAAApril/extended_value_notifier'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

# 发布插件执行命令
# flutter packages pub publish --server=https://pub.dartlang.org
